-- MySQL Script generated by MySQL Workbench
-- Mon Dec 25 11:54:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Steam
-- -----------------------------------------------------
-- Steam游戏数据库
DROP SCHEMA IF EXISTS `Steam` ;

-- -----------------------------------------------------
-- Schema Steam
--
-- Steam游戏数据库
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Steam` DEFAULT CHARACTER SET utf8mb4 ;
SHOW WARNINGS;
USE `Steam` ;

-- -----------------------------------------------------
-- Table `content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `content` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `content` (
  `content_id` INT NOT NULL AUTO_INCREMENT,
  `content_content` TEXT NOT NULL,
  `content_date` TEXT NOT NULL,
  PRIMARY KEY (`content_id`))
ENGINE = InnoDB
COMMENT = '评论';

SHOW WARNINGS;
CREATE UNIQUE INDEX `content_id_UNIQUE` ON `content` (`content_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `content_to_game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `content_to_game` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `content_to_game` (
  `content_id` INT NOT NULL,
  `AppID` INT NOT NULL,
  PRIMARY KEY (`content_id`, `AppID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `content_to_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `content_to_user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `content_to_user` (
  `user_id` INT NOT NULL,
  `content_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `content_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `user_id_UNIQUE` ON `content_to_user` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `content_id_UNIQUE` ON `content_to_user` (`content_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `dev_pub_er`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dev_pub_er` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `dev_pub_er` (
  `dev_pub_id` INT NOT NULL AUTO_INCREMENT,
  `developer_name` VARCHAR(45) NOT NULL,
  `about` TEXT NULL,
  `img` TEXT NULL,
  PRIMARY KEY (`dev_pub_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `developer_id_UNIQUE` ON `dev_pub_er` (`dev_pub_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `developer_to_game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `developer_to_game` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `developer_to_game` (
  `developer_id` INT NOT NULL,
  `AppID` INT NOT NULL,
  PRIMARY KEY (`developer_id`, `AppID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `game` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `game` (
  `AppID` INT NOT NULL COMMENT '游戏唯一标识符',
  `game_name` VARCHAR(100) NOT NULL DEFAULT '无',
  `os` TEXT NOT NULL,
  `game_intro_img` TEXT NULL,
  `Recent_reviews` TEXT NOT NULL COMMENT '最近三十天',
  `All_reviews` TEXT NOT NULL COMMENT '全部',
  `Old_price` VARCHAR(20) NOT NULL DEFAULT '0',
  `New_price` VARCHAR(20) NOT NULL DEFAULT '0',
  `issue_date` DATE NOT NULL DEFAULT '2023-01-01',
  `developer_id` INT NOT NULL DEFAULT -1,
  `publisher_id` INT NOT NULL DEFAULT -1,
  PRIMARY KEY (`AppID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `AppID_UNIQUE` ON `game` (`AppID` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `game_name_UNIQUE` ON `game` (`game_name` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `game_library`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `game_library` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `game_library` (
  `AppID` INT NOT NULL,
  `game_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`AppID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `AppID_UNIQUE` ON `game_library` (`AppID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `game_to_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `game_to_tag` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `game_to_tag` (
  `AppID` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`AppID`, `tag_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `month_rank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `month_rank` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `month_rank` (
  `Date` DATE NOT NULL,
  `AppID` INT NOT NULL,
  PRIMARY KEY (`Date`, `AppID`))
ENGINE = InnoDB
COMMENT = '月新品前20';

SHOW WARNINGS;
CREATE INDEX `Date` ON `month_rank` (`Date` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `AppID` ON `month_rank` (`AppID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `query_record`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `query_record` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `query_record` (
  `record_ID` INT NOT NULL AUTO_INCREMENT,
  `query_time` DATE NOT NULL,
  `query_content` TEXT NOT NULL COMMENT '不同标签用\'/\'连接',
  PRIMARY KEY (`record_ID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `record_ID_UNIQUE` ON `query_record` (`record_ID` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tag` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tag` (
  `tag_id` INT NOT NULL AUTO_INCREMENT COMMENT 'tag唯一标识符',
  `tag_name` VARCHAR(45) NOT NULL COMMENT '标签名',
  `tag_type` TINYINT NOT NULL DEFAULT 0 COMMENT '标签类型 0-系统的 1-普通的',
  `user_id` INT NOT NULL DEFAULT 1,
  `tag_times` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`tag_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `tag_id_UNIQUE` ON `tag` (`tag_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `tag_name_UNIQUE` ON `tag` (`tag_name` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user` (
  `user_id` INT NOT NULL DEFAULT 2 COMMENT '用户唯一标识符',
  `user_account` VARCHAR(20) NOT NULL COMMENT '用户账号',
  `user_password` VARCHAR(20) NOT NULL COMMENT '用户密码',
  `user_gender` VARCHAR(10) NOT NULL DEFAULT '不显示' COMMENT '用户性别',
  `user_email` VARCHAR(45) NULL COMMENT '用户邮箱',
  `user_status` INT NOT NULL DEFAULT 0 COMMENT '用户状态 0-不在线  1-在线  -1-注销',
  `user_admin` TINYINT NOT NULL DEFAULT 0 COMMENT '0-普通用户\n1-系统管理员',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `user_id_UNIQUE` ON `user` (`user_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `user_account_UNIQUE` ON `user` (`user_account` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user_to_query`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_to_query` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user_to_query` (
  `record_ID` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`record_ID`, `user_id`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `user_to_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_to_tag` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `user_to_tag` (
  `user_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  PRIMARY KEY (`tag_id`, `user_id`))
ENGINE = InnoDB
COMMENT = '联合表';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `week_rank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `week_rank` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `week_rank` (
  `Date` DATE NOT NULL,
  `AppID` INT NOT NULL,
  `rank` INT NOT NULL,
  PRIMARY KEY (`Date`, `AppID`, `rank`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `Date` ON `week_rank` (`Date` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `year_rank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `year_rank` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `year_rank` (
  `Date` DATE NOT NULL,
  `AppID` INT NOT NULL,
  `category` VARCHAR(45) NOT NULL DEFAULT '无',
  PRIMARY KEY (`Date`, `AppID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `Date` ON `year_rank` (`Date` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `AppID` ON `year_rank` (`AppID` ASC) INVISIBLE;

SHOW WARNINGS;
CREATE INDEX `category` ON `year_rank` (`category` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
